version: '3.1'
services:
  wordpress:
    image: wordpress
    container_name: apptv
    restart: always
    ports: 
      - 5020:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: senac 
      WORDPRESS_DB_PASSWORD: 123@senac
      WORDPRESS_DB_NAME: dbtv
    volumes:
      - ~/assistenciatv/apptv:/var/www/html
  db:
    image: mysql:latest
    container_name: bancotv
    restart: always
    ports:
      - 6010:3306
    environment:
     MYSQL_DATABASE: dbtv
     MYSQL_USER: senac
     MYSQL_PASSWORD: 123@senac
     MYSQL_ROOT_PASSWORD: 123@senac
    volumes:
     - ~/assistenciatv/dbtv:/var/lib/mysql
